#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(MEGA_PUNCH) \
    F(CHARM) \
    F(FAKE_TEARS) \
    F(SWORDS_DANCE) \
    F(DRAIN_PUNCH) \
    F(LOW_KICK) \
    F(ACID_SPRAY) \
    F(FALSE_SWIPE) \
    F(CURSE) \
    F(ROUND) \
    F(SOLAR_BEAM) \
    F(SOLAR_BLADE) \
    F(REFLECT) \
    F(LIGHT_SCREEN) \
    F(SAFEGUARD) \
    F(TRICK) \
    F(REST) \
    F(ROCK_TOMB) \
    F(GIGA_DRAIN) \
    F(BULLET_SEED) \
    F(ENERGY_BALL) \
    F(THIEF) \
    F(ICY_WIND) \
    F(FACADE) \
    F(PROTECT) \
    F(TAUNT) \
    F(HYPER_BEAM) \
    F(GIGA_IMPACT) \
    F(AERIAL_ACE) \
    F(CHILLING_WATER) \
    F(PSYCHIC_FANGS) \
    F(THUNDER_FANG) \
    F(ICE_FANG) \
    F(FIRE_FANG) \
    F(AIR_SLASH) \
    F(DARK_PULSE) \
    F(SHADOW_BALL) \
    F(WILL_O_WISP) \
    F(IMPRISON) \
    F(PSYCHIC_NOISE) \
    F(PSYSHOCK) \
    F(PSYCHIC) \
    F(FOUL_PLAY) \
    F(TOXIC) \
    F(ROOST) \
    F(HELPING_HAND) \
    F(RETURN) \
    F(FRUSTRATION) \
    F(POWER_GEM) \
    F(BRICK_BREAK) \
    F(ROCK_SLIDE) \
    F(STONE_EDGE) \
    F(EARTH_POWER) \
    F(DIG) \
    F(EARTHQUAKE) \
    F(SUNNY_DAY) \
    F(RAIN_DANCE) \
    F(SNOWSCAPE) \
    F(SANDSTORM) \
    F(SNARL) \
    F(BREAKING_SWIPE) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(FLAMETHROWER) \
    F(FIRE_BLAST) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(DRAGON_PULSE) \
    F(VOLT_SWITCH) \
    F(WILD_CHARGE) \
    F(SKILL_SWAP) \
    F(TRICK_ROOM) \
    F(DAZZLING_GLEAM) \
    F(PLAY_ROUGH) \
    F(U_TURN) \
    F(FLING) \
    F(SHADOW_CLAW) \
    F(HYPER_VOICE) \
    F(IRON_HEAD) \
    F(HEAVY_SLAM) \
    F(FLASH_CANNON) \
    F(LIQUIDATION) \
    F(SURF) \
    F(HYDRO_PUMP) \
    F(HURRICANE) \
    F(TAILWIND) \
    F(INFESTATION) \
    F(GUNK_SHOT) \
    F(WEATHER_BALL) \
    F(THUNDER_WAVE) \
    F(SLUDGE_BOMB) \
    F(POISON_JAB) \
    F(BUG_BUZZ) \
    F(LEECH_LIFE) \
    F(BODY_PRESS) \
    F(ICE_SPINNER) \
    F(POLTERGEIST) \
    F(ACROBATICS) \
    F(SUBSTITUTE) \
    F(DRAGON_CLAW)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SPLASH) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
